### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by demajistre** [NASA-AMMOS/seq-json-schema#22]
When I use the instructions for pip instal `pip install seq-json-schema`, I get the following error:

Collecting seq-json-schema
  Using cached seq-json-schema-1.0.20.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/m6/1ls9h6ps0kn7jgklb437svmc0000gn/T/pip-install-xgxd5ptk/seq-json-schema_ec8cd486a5d54229b57993cfd3a8a511/setup.py", line 8, in <module>
          with open(this_directory / 'package.json', 'r') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m6/1ls9h6ps0kn7jgklb437svmc0000gn/T/pip-install-xgxd5ptk/seq-json-schema_ec8cd486a5d54229b57993cfd3a8a511/package.json'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cohansen** [comment]
Possibly fixed with #23, please test and let me know!
